//
//  AWEventConstants.h
//  PurchaseSDK
//
//  Created by yikunHuang on 2022/6/7.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN


FOUNDATION_EXPORT NSString * const NAME_INIT;
FOUNDATION_EXPORT NSString * const KEY_INIT_START;
FOUNDATION_EXPORT NSString * const KEY_INIT_SUCCESS;
FOUNDATION_EXPORT NSString * const KEY_INIT_FAILED;

FOUNDATION_EXPORT NSString * const NAME_REQUEST_PRODUCT;
FOUNDATION_EXPORT NSString * const KEY_REQUEST_PRODUCT_START;
FOUNDATION_EXPORT NSString * const KEY_REQUEST_PRODUCT_SUCCESS;
FOUNDATION_EXPORT NSString * const KEY_REQUEST_PRODUCT_FAILED;

FOUNDATION_EXPORT NSString * const NAME_PURCHASE;
FOUNDATION_EXPORT NSString * const KEY_PURCHASE_START;
FOUNDATION_EXPORT NSString * const KEY_PURCHASE_SUCCESS;
FOUNDATION_EXPORT NSString * const KEY_PURCHASE_FAILED;

FOUNDATION_EXPORT NSString * const NAME_RESTORE;
FOUNDATION_EXPORT NSString * const KEY_RESTORE_START;
FOUNDATION_EXPORT NSString * const KEY_RESTORE_SUCCESS;
FOUNDATION_EXPORT NSString * const KEY_RESTORE_FAILED;

@interface AWEventConstants : NSObject

@end

NS_ASSUME_NONNULL_END
